### ISSUE TITLE
documentation generator

### ISSUE THREAD

**Issue by AnthonyBuisset** [onlydustxyz/kaaper#6]
### Details
As a developer I want to generate the documentation of my code so that I can publish it.

doxygen-like tool to generate documentation (from comment and code parsing)
modular approach to choose the generated format. 3 step approach:
1. parse code and comments to generate temporary output in machine readable format
2. translate the output into human readable documentation (html, markdown, ...)
3. _(optional)_ Publish documentation 

### Acceptance Criteria
- The documentation is being generated in at least one format
- The documentation can be published **OR** a new issue is being created with this requirement
- The content of the documentation comments and badic info from the code are part of the documentation

### References
- Documentation comment standard to be delivered by #4

**Comment by internnos** [comment]
hi i want to propose this

so the interface for `ParsingResult` is as follows

```
interface ParsingResult {
  attributeName: string;
  functionName: string;
  functionSignature: {
    implicitArgs: FunctionSignature[] | null;
    explicitArgs: FunctionSignature[] | null;
    returns: FunctionSignature[] | null;
  };
  functionComment: {
    desc: FunctionComment[] | null;
    implicitArgs: FunctionComment[] | null;
    explicitArgs: FunctionComment[] | null;
    returns: FunctionComment[] | null;
    raises: FunctionComment[] | null;
  };
}
```

where `FunctionComment` is as follows

```
interface FunctionComment {
  name: string;
  type: string;
  desc: string;
}
```

i propose to generate this into `yaml` first instead of human readable format, since
1. it would be easier for to consume the yaml (without the direct dependency to this repo) 
2. easier to validate
3. provide baseline
4. yaml is easier to read than json

later we can open issue to generate this in different format other than yaml

**Comment by AnthonyBuisset** [comment]
yes, let's start with yaml and open issues to support other formats
